return {
	"xiyaowong/transparent.nvim",
	lazy = false,
	opts = {
		groups = {
			"Normal",
			"NormalNC",
			"Comment",
			"Constant",
			"Special",
			"Identifier",
			"Statement",
			"PreProc",
			"Type",
			"Underlined",
			"Todo",
			"String",
			"Function",
			"Conditional",
			"Repeat",
			"Operator",
			"Structure",
			"LineNr",
			"NonText",
			"SignColumn",
			"CursorLine",
			"CursorLineNr",
			"StatusLine",
			"StatusLineNC",
			"EndOfBuffer",
		},
		extra_groups = {
			"NeoTreeNormal",
			"NeoTreeNormalNC",
			"NeoTreeEndOfBuffer",
			"NeoTreeWinSeparator",
			"NeoTreeStatusLine",
			"NeoTreeStatusLineNC",

			"NeoTreeFloatNormal",
			"NeoTreeFloatBorder",

			"TelescopeNormal",
			"TelescopeBorder",
			"TelescopePromptNormal",
			"TelescopePromptBorder",
			"TelescopeResultsNormal",
			"TelescopeResultsBorder",
			"TelescopePreviewNormal",
			"TelescopePreviewBorder",
			"TelescopePromptTitle",
			"TelescopeResultsTitle",
			"TelescopePreviewTitle",
		},
	},
}
