return {
  "xiyaowong/transparent.nvim",
  lazy = false,
  opts = {
    groups = {
      "Normal",
      "NormalNC",
      "Comment",
      "Constant",
      "Special",
      "Identifier",
      "Statement",
      "PreProc",
      "Type",
      "Underlined",
      "Todo",
      "String",
      "Function",
      "Conditional",
      "Repeat",
      "Operator",
      "Structure",
      "LineNr",
      "NonText",
      "SignColumn",
      "CursorLine",
      "CursorLineNr",
      "StatusLine",
      "StatusLineNC",
      "EndOfBuffer",
    },
    extra_groups = {
      "NvimTreeNormal",
      "NvimTreeNormalNC",
      "NvimTreeEndOfBuffer",
      "NvimTreeVertSplit",
      "NvimTreeWinSeparator",
      "NvimTreeCursorLine",
      "NvimTreeCursorLineNr",

      "TelescopeNormal",
      "TelescopeBorder",
      "TelescopePromptNormal",
      "TelescopePromptBorder",
      "TelescopeResultsNormal",
      "TelescopeResultsBorder",
      "TelescopePreviewNormal",
      "TelescopePreviewBorder",
      "TelescopePromptTitle",
      "TelescopeResultsTitle",
      "TelescopePreviewTitle",

      "NoiceNormal",
      "NoiceBorder",
      "NoiceCmdlinePopup",
      "NoiceCmdlinePopupBorder",
      "NoiceCmdlinePopupTitle",
      "NoicePopup",
      "NoicePopupBorder",
      "NoiceConfirm",
      "NoiceConfirmBorder",

      "BufferLineFill",
      "BufferLineBackground",
      "BufferLineBuffer",
      "BufferLineBufferSelected",
      "BufferLineBufferVisible",
      "BufferLineSeparator",
      "BufferLineSeparatorSelected",
      "BufferLineIndicatorSelected",
    },
  },
}
